name: Create ospsuite.reportingengine Linux images
on: push

jobs:
  build:
    strategy:
        fail-fast: ${{ github.event_name == 'release' }}
        matrix:
            r_version: [4.1.0]
            os_version: [bionic]
    runs-on: ubuntu-latest
    env:
        OSPSUITE_R_VERSION: 11.0.123
        REPORTINGENGINE_VERSION: 2.2.322
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile
          build-args: |
            r_version=${{ matrix.r_version }}
            os_version=${{ matrix.os_version }}
            ospsuite_r_version=${{ env.OSPSUITE_R_VERSION }}
            re_version=${{ env.REPORTINGENGINE_VERSION }}
          push: true
          tags: |
            ghcr.io/yuri05/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ env.REPORTINGENGINE_VERSION }}
            ghcr.io/yuri05/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
#          labels: |
#            ghcr.io/yuri05/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ env.REPORTINGENGINE_VERSION }}
#            ghcr.io/yuri05/reporting.engine-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
